// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eawutspxunldlkfesgik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhd3V0c3B4dW5sZGxrZmVzZ2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0OTgzNDAsImV4cCI6MjA1MzA3NDM0MH0.rGQcAXR7E6dOUhd8dMNZ7r4AzPZkYWH5OL2RX9JFZjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);